Сделал ДЗ 19, Дз неполная, потому что многое не понятно
Karenanna/hw19 pull request #1
Opened 2022-11-24 09:50 UTC by Karenanna

Проверьте пожалуйста ДЗ 19, очень сложно было для меня

2022-11-24 17:08 UTC, OlgaLugacheva requested changes

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Transport.java
> +public class Transport {
класс может быть абстрактным так как нам не понадобятся экземпляры этого класса

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Transport.java
> +
нужен абстрактный метод refill
что-то вроде
abstract void refill();

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Transport.java
> +        }
раз тут есть проверка, тогда нужно установить какой-то дефолтное значение, на твой выбор - любое

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Transport.java
> +        this.model = model;
это должно попасть в блок else

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Bus.java
> +        this(brand,model,productionYear,produtionCountry,color,maxSpeed);
эта строка все-таки не нужна

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Bus.java
> +    }
в этом классе и прочих наследниках refill нужно переопределить
    @Override
    void refill() {
     //здесь какая-то логика   - вывод написать самому
    }

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Train.java
> +    }
тут скорее конструктор должен выглядеть так
```
public Train(String brand, String model, int productionYear, String produtionCountry,  int maxSpeed, String departs, String goTo, double cost, int vagons, String color) {
        super(brand, model, productionYear, produtionCountry, color, maxSpeed); //это родительский конструктор
        this.departs = departs; //а этих паарметров в родителе нет - мы должны проинициализировать их самостоятельно
        this.goTo = goTo;
//продолжить самому
    }
```


аналогично нужно поправить остальные классы

2022-11-24 17:08 UTC, OlgaLugacheva commented on src/Train.java
> +    public int vagons;
здесь нужны не все параметры, а только те, которых нет в родителе

2022-11-25 21:44 UTC, Karenanna commented
Спасибо Вам за помощь, Ваше замечание очень помогли понять суть урока

2022-11-28 19:57 UTC, merged

2022-11-28 22:47 UTC, Karenanna commented
проверьте ДЗ

2022-11-30 09:17 UTC, Karenanna commented
Проверьте пожалуйста ДЗ, спасибо Вам за помощь.

2022-12-01 20:50 UTC, Karenanna commented
проверьте пожалуйста ДЗ